version: 1.0.{build}
image: Ubuntu1804
build_script:
- sh: make release sys=windows-amd64 buildtags="experimental"
test: off
deploy:
- provider: GitHub
  tag: v${appveyor_build_version}
  release: lnd-v${appveyor_build_version}
  auth_token:
    secure: yrYqUuJOQQ2tuGG/cO+HCibFyO8krNX9b45ZxX75uZXJn+6aVdeB/q4tmxm/0gHH
