version: 1.0.{build}
image: Ubuntu1804
skip_tags: true
environment:
  GITHUB_TOKEN:
    secure: eX0omHrG+u98lJiRLG22/bIHWT/zn7YMK86CW6JcHYnYHx83hfpDytzM7qwwyMNH
before_build:
- sh: export COMMIT_LOG=`git log -1 --format='%ci %H %s'`
- sh: npm install -g github-release-cli
build_script:
- sh: make release sys=windows-amd64 buildtags="experimental"
- sh: cd ~/projects/lnd && github-release upload --owner=Emad-salah --repo=lnd --tag=APPVEYOR_BUILD_VERSION --name="${TRAVIS_BRANCH}" --body="${COMMIT_LOG}" "lnd-windows*.zip"
test: off
# deploy:
# - provider: GitHub
#   tag: v$(APPVEYOR_BUILD_VERSION)
#   release: lnd-v$(APPVEYOR_BUILD_VERSION)
#   artifact: windows-package
#   auth_token:
#     secure: yrYqUuJOQQ2tuGG/cO+HCibFyO8krNX9b45ZxX75uZXJn+6aVdeB/q4tmxm/0gHH
