# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "*/15 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.0.0
      with:
        # GitHub public repo slug or full https clone url (with access_token if needed)
        source_repo: lightningnetwork/lnd
        # Branch name to sync from
        source_branch: master
        # Branch name to sync to in this repo
        destination_branch: master
        # GitHub token secret
        github_token: ${{ secrets.GITHUB_TOKEN }}
